# JPA
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://my-mysql.cdokwwuykz7h.ap-northeast-2.rds.amazonaws.com:3306/byeoljali?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: t!20110419
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  redis:
    host: i10e104.p.ssafy.io
    port: 6379
    password: 'ssafy'
  profiles:
    include: oauth
  openvidu:
    url: https://i10e104.p.ssafy.io:8443
    secret: 'MY_SECRET'
  mail:
    host: smtp.gmail.com
    port: 587
    username: byeoljali
    password: gjqm omzh vrwf keav
    properties:
      debug: true
      stmp:
        connectiontimeout: 5000
        starttls:
          enable: true
        ssl:
          enable: false
logging.level:
  org.hibernate.SQL: debug


cloud:
  aws:
    s3:
      bucket: 'testbyeoljari'
    credentials:
      access-key: 'AKIA2XMTXK5MPFBZ3PSM'
      secret-key: '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'
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false