spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 'aa942ad78b7dca415ad4c16b40ef95d2'
            client-secret: 'Ih48q40vxhB3U37ThaAMCVcVkgvjH9k6'
            redirect-uri: 'http://localhost:3000'
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: kakao
            scope: profile, account_email, profile_image
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
