spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
#            client-id: 'aa942ad78b7dca415ad4c16b40ef95d2'
            client-id: '13e2daef357ed33894d3c75e4bb31528'
#            client-secret: 'Ih48q40vxhB3U37ThaAMCVcVkgvjH9k6'
            client-secret: 'K1a9nGhfnXYCDTd3gMYUnAB1njYyQjgz'
            redirect-uri: 'https://i10e104.p.ssafy.io/'
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: kakao
            scope: profile, account_email, profile_image
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
