spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: '218aa28a9e8fa4d947c106cb95b2ec1b'
            client-secret: 'J1m0S3gVIYlbmapbFaACyQSrwDD8fEXF'
            redirect-uri: localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope: profile, account_email, profile_image
